//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mpts.Applications.ACVerify.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SuppressCommonAssembliesInconsistancy {
            get {
                return ((bool)(this["SuppressCommonAssembliesInconsistancy"]));
            }
            set {
                this["SuppressCommonAssembliesInconsistancy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mscorlib")]
        public string CommonAssembliesSeparatedBySemicolon {
            get {
                return ((string)(this["CommonAssembliesSeparatedBySemicolon"]));
            }
            set {
                this["CommonAssembliesSeparatedBySemicolon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SuppressAssembliesThatConainsOnlyResourcesForParticularCulture {
            get {
                return ((bool)(this["SuppressAssembliesThatConainsOnlyResourcesForParticularCulture"]));
            }
            set {
                this["SuppressAssembliesThatConainsOnlyResourcesForParticularCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadAssembliesIntoDifferentDomain {
            get {
                return ((bool)(this["LoadAssembliesIntoDifferentDomain"]));
            }
            set {
                this["LoadAssembliesIntoDifferentDomain"] = value;
            }
        }
    }
}
